from kozmo_ai.errors.base import KozmoBaseException


class UnauthenticatedRequestException(KozmoBaseException):
    pass
